"""Drum kit presets with synthesis parameters for each drum type."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class DrumSoundParams:
    """Synthesis parameters for a single drum sound type."""

    osc_waveform: str = "sine"
    pitch_start: float = 150.0
    pitch_end: float = 50.0
    pitch_decay: float = 0.04
    amp_attack: float = 0.001
    amp_decay: float = 0.2
    noise_level: float = 0.0
    noise_decay: float = 0.05
    tone_level: float = 1.0
    fm_mod_index: float = 0.0
    fm_mod_ratio: float = 1.0
    filter_type: str = "lowpass"
    filter_cutoff: float = 5000.0
    filter_resonance: float = 0.0
    filter_env_amount: float = 0.0
    filter_decay: float = 0.1
    distortion_drive: float = 0.0
    bit_crush: float = 0.0


@dataclass
class DrumKitPreset:
    """A complete drum kit with parameters for every drum type."""

    name: str
    description: str = ""
    kick: DrumSoundParams = field(default_factory=DrumSoundParams)
    snare: DrumSoundParams = field(default_factory=DrumSoundParams)
    hh_closed: DrumSoundParams = field(default_factory=DrumSoundParams)
    hh_open: DrumSoundParams = field(default_factory=DrumSoundParams)
    clap: DrumSoundParams = field(default_factory=DrumSoundParams)
    crash: DrumSoundParams = field(default_factory=DrumSoundParams)
    tom_high: DrumSoundParams = field(default_factory=DrumSoundParams)
    tom_mid: DrumSoundParams = field(default_factory=DrumSoundParams)
    tom_low: DrumSoundParams = field(default_factory=DrumSoundParams)
    rim: DrumSoundParams = field(default_factory=DrumSoundParams)

    def get_params(self, drum_type: str) -> DrumSoundParams:
        """Get parameters for a specific drum type."""
        mapping: dict[str, DrumSoundParams] = {
            "kick": self.kick,
            "snare": self.snare,
            "hh_closed": self.hh_closed,
            "hh_open": self.hh_open,
            "clap": self.clap,
            "crash": self.crash,
            "tom_high": self.tom_high,
            "tom_mid": self.tom_mid,
            "tom_low": self.tom_low,
            "rim": self.rim,
        }
        return mapping.get(drum_type, DrumSoundParams())


DRUM_KIT_PRESETS: dict[str, DrumKitPreset] = {
    "909 House": DrumKitPreset(
        name="909 House",
        description="Punchy electronic kicks with crisp hi-hats — classic Roland TR-909 inspired",
        kick=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=180.0,
            pitch_end=45.0,
            pitch_decay=0.05,
            amp_attack=0.001,
            amp_decay=0.22,
            noise_level=0.08,
            noise_decay=0.015,
            distortion_drive=0.3,
        ),
        snare=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=200.0,
            pitch_end=180.0,
            pitch_decay=0.1,
            amp_attack=0.001,
            amp_decay=0.18,
            noise_level=0.7,
            noise_decay=0.12,
            tone_level=0.4,
            filter_type="bandpass",
            filter_cutoff=1200.0,
            filter_resonance=0.3,
            distortion_drive=0.15,
        ),
        hh_closed=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.04,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.05,
            filter_type="highpass",
            filter_cutoff=9000.0,
            filter_resonance=0.2,
        ),
        hh_open=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.35,
            tone_level=0.0,
            amp_attack=0.005,
            amp_decay=0.4,
            filter_type="highpass",
            filter_cutoff=7000.0,
            filter_resonance=0.2,
        ),
        clap=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.18,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.2,
            filter_type="bandpass",
            filter_cutoff=1500.0,
            filter_resonance=0.2,
            distortion_drive=0.1,
        ),
        crash=DrumSoundParams(
            noise_level=1.0,
            noise_decay=2.0,
            tone_level=0.0,
            amp_attack=0.01,
            amp_decay=2.5,
            filter_type="highshelf",
            filter_cutoff=8000.0,
            distortion_drive=0.05,
        ),
        tom_high=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=400.0,
            pitch_end=200.0,
            pitch_decay=0.08,
            amp_attack=0.003,
            amp_decay=0.25,
            noise_level=0.03,
            noise_decay=0.02,
            distortion_drive=0.05,
        ),
        tom_mid=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=250.0,
            pitch_end=120.0,
            pitch_decay=0.08,
            amp_attack=0.003,
            amp_decay=0.28,
            noise_level=0.03,
            noise_decay=0.02,
            distortion_drive=0.05,
        ),
        tom_low=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=150.0,
            pitch_end=80.0,
            pitch_decay=0.08,
            amp_attack=0.003,
            amp_decay=0.3,
            noise_level=0.03,
            noise_decay=0.02,
            distortion_drive=0.05,
        ),
        rim=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=1000.0,
            pitch_end=800.0,
            pitch_decay=0.01,
            amp_attack=0.001,
            amp_decay=0.03,
            noise_level=0.3,
            noise_decay=0.01,
            tone_level=0.6,
            filter_type="highpass",
            filter_cutoff=6000.0,
        ),
    ),
    "808 Classic": DrumKitPreset(
        name="808 Classic",
        description="Deep booming bass, long decay — Roland TR-808 inspired",
        kick=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=120.0,
            pitch_end=35.0,
            pitch_decay=0.12,
            amp_attack=0.002,
            amp_decay=0.5,
            noise_level=0.05,
            noise_decay=0.01,
            distortion_drive=0.15,
        ),
        snare=DrumSoundParams(
            osc_waveform="triangle",
            pitch_start=250.0,
            pitch_end=220.0,
            pitch_decay=0.08,
            amp_attack=0.001,
            amp_decay=0.15,
            noise_level=0.8,
            noise_decay=0.1,
            tone_level=0.3,
            filter_type="bandpass",
            filter_cutoff=800.0,
            distortion_drive=0.05,
        ),
        hh_closed=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.05,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.06,
            filter_type="highpass",
            filter_cutoff=10000.0,
        ),
        hh_open=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.5,
            tone_level=0.0,
            amp_attack=0.005,
            amp_decay=0.6,
            filter_type="highpass",
            filter_cutoff=7500.0,
        ),
        clap=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.2,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.22,
            filter_type="bandpass",
            filter_cutoff=1300.0,
        ),
        crash=DrumSoundParams(
            noise_level=1.0,
            noise_decay=2.5,
            tone_level=0.0,
            amp_attack=0.015,
            amp_decay=3.0,
            filter_type="highshelf",
            filter_cutoff=7000.0,
        ),
        tom_high=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=350.0,
            pitch_end=180.0,
            pitch_decay=0.1,
            amp_attack=0.003,
            amp_decay=0.3,
        ),
        tom_mid=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=220.0,
            pitch_end=100.0,
            pitch_decay=0.1,
            amp_attack=0.003,
            amp_decay=0.35,
        ),
        tom_low=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=160.0,
            pitch_end=65.0,
            pitch_decay=0.12,
            amp_attack=0.002,
            amp_decay=0.45,
            distortion_drive=0.08,
        ),
        rim=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=900.0,
            pitch_end=700.0,
            pitch_decay=0.008,
            amp_attack=0.001,
            amp_decay=0.025,
            noise_level=0.2,
            noise_decay=0.008,
            tone_level=0.5,
            filter_type="highpass",
            filter_cutoff=5000.0,
        ),
    ),
    "EDM Punchy": DrumKitPreset(
        name="EDM Punchy",
        description="Aggressive, saturated, cut-through-the-mix festival drums",
        kick=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=200.0,
            pitch_end=40.0,
            pitch_decay=0.04,
            amp_attack=0.001,
            amp_decay=0.18,
            noise_level=0.1,
            noise_decay=0.01,
            fm_mod_index=0.3,
            distortion_drive=0.5,
        ),
        snare=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=220.0,
            pitch_end=190.0,
            pitch_decay=0.06,
            amp_attack=0.001,
            amp_decay=0.2,
            noise_level=0.9,
            noise_decay=0.15,
            tone_level=0.5,
            filter_type="bandpass",
            filter_cutoff=1000.0,
            filter_resonance=0.4,
            distortion_drive=0.35,
        ),
        hh_closed=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.03,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.04,
            filter_type="highpass",
            filter_cutoff=11000.0,
            distortion_drive=0.1,
        ),
        hh_open=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.3,
            tone_level=0.0,
            amp_attack=0.003,
            amp_decay=0.35,
            filter_type="highpass",
            filter_cutoff=8000.0,
            distortion_drive=0.05,
        ),
        clap=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.16,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.18,
            filter_type="bandpass",
            filter_cutoff=1800.0,
            distortion_drive=0.2,
        ),
        crash=DrumSoundParams(
            noise_level=1.0,
            noise_decay=1.8,
            tone_level=0.0,
            amp_attack=0.008,
            amp_decay=2.0,
            filter_type="highshelf",
            filter_cutoff=9000.0,
            distortion_drive=0.1,
        ),
        tom_high=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=420.0,
            pitch_end=200.0,
            pitch_decay=0.06,
            amp_attack=0.002,
            amp_decay=0.2,
            distortion_drive=0.1,
        ),
        tom_mid=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=280.0,
            pitch_end=130.0,
            pitch_decay=0.06,
            amp_attack=0.002,
            amp_decay=0.22,
            distortion_drive=0.1,
        ),
        tom_low=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=180.0,
            pitch_end=70.0,
            pitch_decay=0.07,
            amp_attack=0.002,
            amp_decay=0.25,
            noise_level=0.03,
            noise_decay=0.01,
            distortion_drive=0.15,
        ),
        rim=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=1100.0,
            pitch_end=850.0,
            pitch_decay=0.006,
            amp_attack=0.001,
            amp_decay=0.02,
            noise_level=0.25,
            noise_decay=0.006,
            tone_level=0.7,
            filter_type="highpass",
            filter_cutoff=7000.0,
        ),
    ),
    "Trap Kit": DrumKitPreset(
        name="Trap Kit",
        description="Ultra-deep 808s, snappy snares, rapid hi-hat rolls",
        kick=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=100.0,
            pitch_end=28.0,
            pitch_decay=0.2,
            amp_attack=0.003,
            amp_decay=0.8,
            noise_level=0.03,
            noise_decay=0.01,
            distortion_drive=0.25,
        ),
        snare=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=200.0,
            pitch_end=170.0,
            pitch_decay=0.05,
            amp_attack=0.001,
            amp_decay=0.12,
            noise_level=0.6,
            noise_decay=0.08,
            tone_level=0.3,
            filter_type="bandpass",
            filter_cutoff=1100.0,
            filter_resonance=0.25,
            distortion_drive=0.2,
        ),
        hh_closed=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.025,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.03,
            filter_type="highpass",
            filter_cutoff=12000.0,
        ),
        hh_open=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.25,
            tone_level=0.0,
            amp_attack=0.002,
            amp_decay=0.3,
            filter_type="highpass",
            filter_cutoff=8500.0,
        ),
        clap=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.14,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.16,
            filter_type="bandpass",
            filter_cutoff=1600.0,
        ),
        crash=DrumSoundParams(
            noise_level=1.0,
            noise_decay=2.2,
            tone_level=0.0,
            amp_attack=0.01,
            amp_decay=2.8,
            filter_type="highshelf",
            filter_cutoff=7500.0,
        ),
        tom_high=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=380.0,
            pitch_end=180.0,
            pitch_decay=0.1,
            amp_attack=0.003,
            amp_decay=0.28,
        ),
        tom_mid=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=240.0,
            pitch_end=110.0,
            pitch_decay=0.12,
            amp_attack=0.003,
            amp_decay=0.32,
        ),
        tom_low=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=140.0,
            pitch_end=55.0,
            pitch_decay=0.15,
            amp_attack=0.002,
            amp_decay=0.5,
            distortion_drive=0.12,
        ),
        rim=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=1050.0,
            pitch_end=780.0,
            pitch_decay=0.005,
            amp_attack=0.001,
            amp_decay=0.018,
            noise_level=0.2,
            noise_decay=0.005,
            tone_level=0.65,
            filter_type="highpass",
            filter_cutoff=6500.0,
        ),
    ),
    "Lo-Fi Crunch": DrumKitPreset(
        name="Lo-Fi Crunch",
        description="Degraded, warm, tape-like character with bit crushing",
        kick=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=130.0,
            pitch_end=50.0,
            pitch_decay=0.06,
            amp_attack=0.002,
            amp_decay=0.25,
            noise_level=0.06,
            noise_decay=0.02,
            distortion_drive=0.2,
            bit_crush=0.3,
        ),
        snare=DrumSoundParams(
            osc_waveform="triangle",
            pitch_start=200.0,
            pitch_end=180.0,
            pitch_decay=0.07,
            amp_attack=0.002,
            amp_decay=0.16,
            noise_level=0.65,
            noise_decay=0.1,
            tone_level=0.35,
            filter_type="bandpass",
            filter_cutoff=900.0,
            distortion_drive=0.15,
            bit_crush=0.25,
        ),
        hh_closed=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.04,
            tone_level=0.0,
            amp_attack=0.001,
            amp_decay=0.05,
            filter_type="highpass",
            filter_cutoff=8000.0,
            bit_crush=0.35,
        ),
        hh_open=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.4,
            tone_level=0.0,
            amp_attack=0.006,
            amp_decay=0.5,
            filter_type="highpass",
            filter_cutoff=6000.0,
            bit_crush=0.25,
        ),
        clap=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.2,
            tone_level=0.0,
            amp_attack=0.002,
            amp_decay=0.22,
            filter_type="bandpass",
            filter_cutoff=1200.0,
            bit_crush=0.3,
        ),
        crash=DrumSoundParams(
            noise_level=1.0,
            noise_decay=2.0,
            tone_level=0.0,
            amp_attack=0.012,
            amp_decay=2.5,
            filter_type="highshelf",
            filter_cutoff=6500.0,
            bit_crush=0.2,
        ),
        tom_high=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=350.0,
            pitch_end=170.0,
            pitch_decay=0.09,
            amp_attack=0.004,
            amp_decay=0.28,
            bit_crush=0.2,
        ),
        tom_mid=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=220.0,
            pitch_end=100.0,
            pitch_decay=0.09,
            amp_attack=0.004,
            amp_decay=0.3,
            bit_crush=0.2,
        ),
        tom_low=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=150.0,
            pitch_end=70.0,
            pitch_decay=0.1,
            amp_attack=0.003,
            amp_decay=0.35,
            distortion_drive=0.1,
            bit_crush=0.2,
        ),
        rim=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=950.0,
            pitch_end=750.0,
            pitch_decay=0.007,
            amp_attack=0.001,
            amp_decay=0.025,
            noise_level=0.25,
            noise_decay=0.007,
            tone_level=0.5,
            filter_type="highpass",
            filter_cutoff=5500.0,
            bit_crush=0.3,
        ),
    ),
    "Acoustic": DrumKitPreset(
        name="Acoustic",
        description="Synthesized acoustic-like drums — warm, natural character",
        kick=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=160.0,
            pitch_end=38.0,
            pitch_decay=0.08,
            amp_attack=0.002,
            amp_decay=0.3,
            noise_level=0.06,
            noise_decay=0.015,
            fm_mod_index=0.15,
            filter_type="lowpass",
            filter_cutoff=3000.0,
            filter_env_amount=0.5,
            filter_decay=0.06,
        ),
        snare=DrumSoundParams(
            osc_waveform="triangle",
            pitch_start=200.0,
            pitch_end=185.0,
            pitch_decay=0.1,
            amp_attack=0.002,
            amp_decay=0.2,
            noise_level=0.55,
            noise_decay=0.15,
            tone_level=0.5,
            filter_type="bandpass",
            filter_cutoff=1000.0,
            filter_resonance=0.3,
        ),
        hh_closed=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.06,
            tone_level=0.0,
            amp_attack=0.002,
            amp_decay=0.08,
            filter_type="highpass",
            filter_cutoff=8000.0,
            filter_resonance=0.3,
        ),
        hh_open=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.6,
            tone_level=0.0,
            amp_attack=0.008,
            amp_decay=0.7,
            filter_type="highpass",
            filter_cutoff=6500.0,
            filter_resonance=0.25,
        ),
        clap=DrumSoundParams(
            noise_level=1.0,
            noise_decay=0.2,
            tone_level=0.0,
            amp_attack=0.002,
            amp_decay=0.22,
            filter_type="bandpass",
            filter_cutoff=1400.0,
        ),
        crash=DrumSoundParams(
            noise_level=1.0,
            noise_decay=2.8,
            tone_level=0.0,
            amp_attack=0.02,
            amp_decay=3.0,
            filter_type="highshelf",
            filter_cutoff=7000.0,
        ),
        tom_high=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=380.0,
            pitch_end=190.0,
            pitch_decay=0.1,
            amp_attack=0.004,
            amp_decay=0.3,
            fm_mod_index=0.08,
        ),
        tom_mid=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=240.0,
            pitch_end=110.0,
            pitch_decay=0.1,
            amp_attack=0.004,
            amp_decay=0.35,
            fm_mod_index=0.08,
        ),
        tom_low=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=170.0,
            pitch_end=70.0,
            pitch_decay=0.12,
            amp_attack=0.003,
            amp_decay=0.4,
        ),
        rim=DrumSoundParams(
            osc_waveform="sine",
            pitch_start=1100.0,
            pitch_end=850.0,
            pitch_decay=0.008,
            amp_attack=0.001,
            amp_decay=0.03,
            noise_level=0.2,
            noise_decay=0.008,
            tone_level=0.5,
            filter_type="highpass",
            filter_cutoff=6000.0,
        ),
    ),
}
